name: Ruff, Test

on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install --system -e ".[dev]"
      - name: Run tests
        env:
          OPENAI_API_KEY: test-key
        run: python -m unittest discover
      - name: Run Pytest
        env:
          OPENAI_API_KEY: fake
          ANTHROPIC_API_KEY: fake
        run: pytest tests
